version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        description: greenweez raw data
        identifier: raw_gz_product
      - name: sales
        description: information regarding our sales
        identifier: raw_gz_sales
        tests: 
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: ship
        description: information regarding our shipping costs
        identifier: raw_gz_ship

      - name: adwords
        description: paid media results with adwords
        identifier: raw_gz_adwords
        tests:
          - unique:
              column_name: "(campaign_key || '-' || date_date)"
          - not_null:
              column_name: campaign_key

      - name: bing
        description: paid media results with bing
        identifier: raw_gz_bing
        tests:
          - unique:
              column_name: "(campaign_key || '-' || date_date)"
          - not_null:
              column_name: campaign_key

      - name: criteo
        description: paid media results with criteo
        identifier: raw_gz_criteo
        tests:
          - unique:
              column_name: "(campaign_key || '-' || date_date)"
          - not_null:
              column_name: campaign_key

      - name: facebook
        description: paid media results with criteo
        identifier: raw_gz_facebook
        tests:
          - unique:
              column_name: "(campaign_key || '-' || date_date)"
          - not_null:
              column_name: campaign_key
models:
  - name: int_campaigns
    description: intermediate table for campaigns
    tests:
      - unique:
            column_name: "(campaign_key || '-' || date_date)"
      - not_null:
            column_name: campaign_key
  - name: int_campaigns_day
    description: campaigns per day
    tests:
      - unique:
          column_name: date_date
      - not_null:
          column_name: date_date
  - name: finance_campaigns_day
    description: finance and ads cost margin per day
    tests:
      - unique:
          column_name: date_date
      - not_null:
          column_name: date_date
    

      